name: TestNG Maven CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout your code

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17  # Change this to your desired Java version

      - name: Build with Maven
        run: mvn clean install  # Replace with your Maven build command

      - name: Run TestNG Tests
        run: mvn test  # This command runs your TestNG tests

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports  # Adjust the path to your test reports